# golangci-lint run
# gofumpt -l -w -s .

linters:
  enable-all: true
  disable:
    - interfacer # Deprecated
    - scopelint # Deprecated
    - golint # Deprecated
    - maligned # Deprecated

    - exhaustivestruct # 'It is not recommended to use it for all files in a project'
    - forbidigo # forbids the use for fmt.Print(f|ln)
    - nlreturn # opinionated
    - paralleltest # causes tests to randomly fail
    - wsl # whitespace linter, slow, aggressive and opinionated

linters-settings:
  cyclop:
    max-complexity: 15 # default value 10 requires unnecessary refactoring
  varnamelen:
    min-name-length: 1 # default value 3 is too short
