version: '2'
linters:
  default: all
  disable:
    - nlreturn
    - noinlineerr
    - wsl_v5
    # retired
    - exhaustruct
    - gomodguard
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    varnamelen:
      min-name-length: 1
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - 'golang.org/x/text'
            - 'github.com/nalgeon/be'
            - 'github.com/bengarrett/zipcmt'
            - 'github.com/bengarrett/retrotxtgo'
            - 'github.com/bengarrett/sauce'
            - 'github.com/dustin/go-humanize'
            - 'github.com/gookit/color'
            - 'github.com/muesli/go-app-paths'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - goconst
          - gochecknoinits
        path: _test\.go
      - linters:
          - funlen
          - gochecknoglobals
        path: main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
