version: "2"
linters:
  default: all
  disable:
    - depguard
    - nlreturn
    - paralleltest
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    varnamelen:
      min-name-length: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - gochecknoinits
        path: _test\.go
      - linters:
          - funlen
          - gochecknoglobals
        path: main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
