# golangci-lint run
# gofumpt -l -w -s .

linters:
  enable-all: true
  disable:
    # Deprecations
    - exportloopref
    # Opinionated
    - depguard # don't care for
    - nlreturn # opinionated
    - paralleltest # excess work for little gain
    - wsl # whitespace linter, aggressive and opinionated

linters-settings:
  cyclop:
    max-complexity: 15 # default value 10 requires unnecessary refactoring
  varnamelen:
    min-name-length: 1 # default value 3 is too short

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - exhaustruct
        - gochecknoinits
    - path: main.go
      linters:
        - funlen
        - gochecknoglobals