# GoReleaser configuration
# https://goreleaser.com
# .goreleaser.yml
#
# To test this tool and config:
# goreleaser healthcheck
# goreleaser check
# goreleaser release --snapshot --clean
#
# To create new repository version tag and push it:
# git tag -a v1.0.1 -m "First release"
# git push origin v1.0.1
#
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
report_sizes: true
before:
  hooks:
    - go mod tidy
builds:
  - id: zipcmt
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64_v1 # apple on intel
      - darwin_arm64_v8.0 # apple silicon
      - freebsd_amd64_v1
      - linux_amd64_v1
      - windows_amd64_v1
archives:
  - id: zipcmt
    name_template: >-
      zipcmt_ {{- if eq .Os "darwin" }} {{- if .Arm64 }}apple_silicon{{ else }}apple_intel_cpu{{ end }} {{- else }}{{ .Os }}{{ end -}}
    files:
      - none*
    formats: ['gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
nfpms:
  - id: Linux
    package_name: "zipcmt"
    file_name_template: "zipcmt"
    vendor: Ben Garrett.
    homepage: https://github.com/bengarrett/zipcmt
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: A batch viewer and extractor for large collections of zip archives.
    license: LGPL 3.0
    formats:
      - apk
      - deb
      - rpm
      - archlinux
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
upx:
  - enabled: false
release:
  footer: >-
    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
